services:
  - type: web
    name: smartrx-drugchecker
    env: dotnet
    buildCommand: dotnet restore && dotnet publish -c Release -o release
    startCommand: cd release && dotnet SmartRx-DrugChecker.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
